[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  publish = "."
  port = 3000

# Handle CORS preflight requests
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://souayah-malek12.github.io"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Credentials = "true"
    Vary = "Origin"

# Handle preflight requests
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://souayah-malek12.github.io"
    Access-Control-Allow-Methods = "OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Credentials = "true"
    Vary = "Origin"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

# API routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200
